reconstruct structured logs

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -36,12 +36,18 @@ jobs:
             | xargs -n1 echo
           )"
 
-          # Log the examples to run
-          echo -e "Running the following examples:\n$examples"
-
           # Run the examples with the current version of Alloy
           for example in $examples; do
+            echo "Running: $example ..."
+            
             cargo run --example $example --quiet 1>/dev/null
+
+            if [ $? -ne 0 ]; then
+              echo "Failed to run: $example"
+              exit 1
+            else
+              echo "Successfully ran: $example"
+            fi
           done
 
           # Fetch the latest commit hash of the main branch from the Alloy repository
@@ -58,6 +64,15 @@ jobs:
 
           # Run the examples with the latest version of Alloy
           for example in $examples; do
+            echo "Running: $example ..."
+
             cargo run --example $example --quiet 1>/dev/null
+
+            if [ $? -ne 0 ]; then
+              echo "Failed to run: $example"
+              exit 1
+            else
+              echo "Successfully ran: $example"
+            fi
           done
         
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,10 +54,16 @@ jobs:
             | xargs -n1 echo
           )"
 
-          # Log the examples to run
-          echo -e "Running the following examples:\n$examples"
-
           # Run the examples
           for example in $examples; do
+            echo "Running: $example ..."
+
             cargo run --example $example --quiet 1>/dev/null
+
+            if [ $? -ne 0 ]; then
+              echo "Failed to run: $example"
+              exit 1
+            else
+              echo "Successfully ran: $example"
+            fi
           done
